
INSERT INTO Countries (name, iso, iso3, dial, currency, currencyName, CurrencySymbol) VALUES
('Albania', 'AL', 'ALB', '355', 'ALL', 'Lek', ''),
('Algeria', 'DZ', 'DZA', '213', 'DZD', 'Algerian Dinar', ''),
('American Samoa', 'AS', 'ASM', '1-684', 'USD', 'US Dollar', ''),
('Andorra', 'AD', 'AND', '376', 'EUR', 'Euro', ''),
('Angola', 'AO', 'AGO', '244', 'AOA', 'Kwanza', ''),
('Anguilla', 'AI', 'AIA', '1-264', 'XCD', 'East Caribbean Dollar', ''),
('Antarctica', 'AQ', 'ATA', '672', '', '', ''),
('Antigua and Barbuda', 'AG', 'ATG', '1-268', 'XCD', 'East Caribbean Dollar', ''),
('Argentina', 'AR', 'ARG', '54', 'ARS', 'Argentine Peso', ''),
('Armenia', 'AM', 'ARM', '374', 'AMD', 'Armenian Dram', ''),
('Aruba', 'AW', 'ABW', '297', 'AWG', 'Aruban Florin', ''),
('Australia', 'AU', 'AUS', '61', 'AUD', 'Australian Dollar', ''),
('Austria', 'AT', 'AUT', '43', 'EUR', 'Euro', ''),
('Azerbaijan', 'AZ', 'AZE', '994', 'AZN', 'Azerbaijanian Manat', ''),
('Bahamas', 'BS', 'BHS', '1-242', 'BSD', 'Bahamian Dollar', ''),
('Bahrain', 'BH', 'BHR', '973', 'BHD', 'Bahraini Dinar', ''),
('Bangladesh', 'BD', 'BGD', '880', 'BDT', 'Taka', ''),
('Barbados', 'BB', 'BRB', '1-246', 'BBD', 'Barbados Dollar', ''),
('Belarus', 'BY', 'BLR', '375', 'BYR', 'Belarussian Ruble', ''),
('Belgium', 'BE', 'BEL', '32', 'EUR', 'Euro', ''),
('Belize', 'BZ', 'BLZ', '501', 'BZD', 'Belize Dollar', ''),
('Benin', 'BJ', 'BEN', '229', 'XOF', 'CFA Franc BCEAO', ''),
('Bermuda', 'BM', 'BMU', '1-441', 'BMD', 'Bermudian Dollar', ''),
('Bhutan', 'BT', 'BTN', '975', 'INR', 'Indian Rupee', ''),
('Bolivia, Plurinational State of', 'BO', 'BOL', '591', 'BOB', 'Boliviano', ''),
('Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', '599', 'USD', 'US Dollar', ''),
('Bosnia and Herzegovina', 'BA', 'BIH', '387', 'BAM', 'Convertible Mark', ''),
('Botswana', 'BW', 'BWA', '267', 'BWP', 'Pula', ''),
('Bouvet Island', 'BV', 'BVT', '47', 'NOK', 'Norwegian Krone', ''),
('Brazil', 'BR', 'BRA', '55', 'BRL', 'Brazilian Real', ''),
('British Indian Ocean Territory', 'IO', 'IOT', '246', 'USD', 'US Dollar', ''),
('Brunei Darussalam', 'BN', 'BRN', '673', 'BND', 'Brunei Dollar', ''),
('Bulgaria', 'BG', 'BGR', '359', 'BGN', 'Bulgarian Lev', ''),
('Burkina Faso', 'BF', 'BFA', '226', 'XOF', 'CFA Franc BCEAO', ''),
('Burundi', 'BI', 'BDI', '257', 'BIF', 'Burundi Franc', ''),
('Cambodia', 'KH', 'KHM', '855', 'KHR', 'Riel', ''),
('Cameroon', 'CM', 'CMR', '237', 'XAF', 'CFA Franc BEAC', ''),
('Canada', 'CA', 'CAN', '1', 'CAD', 'Canadian Dollar', ''),
('Cape Verde', 'CV', 'CPV', '238', 'CVE', 'Cabo Verde Escudo', ''),
('Cayman Islands', 'KY', 'CYM', '1-345', 'KYD', 'Cayman Islands Dollar', ''),
('Central African Republic', 'CF', 'CAF', '236', 'XAF', 'CFA Franc BEAC', ''),
('Chad', 'TD', 'TCD', '235', 'XAF', 'CFA Franc BEAC', ''),
('Chile', 'CL', 'CHL', '56', 'CLP', 'Chilean Peso', ''),
('China', 'CN', 'CHN', '86', 'CNY', 'Yuan Renminbi', ''),
('Christmas Island', 'CX', 'CXR', '61', 'AUD', 'Australian Dollar', ''),
('Cocos (Keeling) Islands', 'CC', 'CCK', '61', 'AUD', 'Australian Dollar', ''),
('Colombia', 'CO', 'COL', '57', 'COP', 'Colombian Peso', ''),
('Comoros', 'KM', 'COM', '269', 'KMF', 'Comoro Franc', ''),
('Congo', 'CG', 'COG', '242', 'XAF', 'CFA Franc BEAC', ''),
('Congo, the Democratic Republic of the', 'CD', 'COD', '243', '', '', ''),
('Cook Islands', 'CK', 'COK', '682', 'NZD', 'New Zealand Dollar', ''),
('Costa Rica', 'CR', 'CRI', '506', 'CRC', 'Costa Rican Colon', ''),
('Croatia', 'HR', 'HRV', '385', 'HRK', 'Croatian Kuna', ''),
('Cuba', 'CU', 'CUB', '53', 'CUP', 'Cuban Peso', ''),
('Curaçao', 'CW', 'CUW', '599', 'ANG', 'Netherlands Antillean Guilder', ''),
('Cyprus', 'CY', 'CYP', '357', 'EUR', 'Euro', ''),
('Czech Republic', 'CZ', 'CZE', '420', 'CZK', 'Czech Koruna', ''),
('Côte d''Ivoire', 'CI', 'CIV', '225', 'XOF', 'CFA Franc BCEAO', ''),
('Denmark', 'DK', 'DNK', '45', 'DKK', 'Danish Krone', ''),
('Djibouti', 'DJ', 'DJI', '253', 'DJF', 'Djibouti Franc', ''),
('Dominica', 'DM', 'DMA', '1-767', 'XCD', 'East Caribbean Dollar', ''),
('Dominican Republic', 'DO', 'DOM', '1-809', 'DOP', 'Dominican Peso', ''),
('Ecuador', 'EC', 'ECU', '593', 'USD', 'US Dollar', ''),
('Egypt', 'EG', 'EGY', '20', 'EGP', 'Egyptian Pound', ''),
('El Salvador', 'SV', 'SLV', '503', 'USD', 'US Dollar', ''),
('Equatorial Guinea', 'GQ', 'GNQ', '240', 'XAF', 'CFA Franc BEAC', ''),
('Eritrea', 'ER', 'ERI', '291', 'ERN', 'Nakfa', ''),
('Estonia', 'EE', 'EST', '372', 'EUR', 'Euro', ''),
('Ethiopia', 'ET', 'ETH', '251', 'ETB', 'Ethiopian Birr', ''),
('Falkland Islands (Malvinas)', 'FK', 'FLK', '500', 'FKP', 'Falkland Islands Pound', ''),
('Faroe Islands', 'FO', 'FRO', '298', 'DKK', 'Danish Krone', ''),
('Fiji', 'FJ', 'FJI', '679', 'FJD', 'Fiji Dollar', ''),
('Finland', 'FI', 'FIN', '358', 'EUR', 'Euro', ''),
('France', 'FR', 'FRA', '33', 'EUR', 'Euro', ''),
('French Guiana', 'GF', 'GUF', '594', 'EUR', 'Euro', ''),
('French Polynesia', 'PF', 'PYF', '689', 'XPF', 'CFP Franc', ''),
('French Southern Territories', 'TF', 'ATF', '262', 'EUR', 'Euro', ''),
('Gabon', 'GA', 'GAB', '241', 'XAF', 'CFA Franc BEAC', ''),
('Gambia', 'GM', 'GMB', '220', 'GMD', 'Dalasi', ''),
('Georgia', 'GE', 'GEO', '995', 'GEL', 'Lari', ''),
('Germany', 'DE', 'DEU', '49', 'EUR', 'Euro', ''),
('Ghana', 'GH', 'GHA', '233', 'GHS', 'Ghana Cedi', ''),
('Gibraltar', 'GI', 'GIB', '350', 'GIP', 'Gibraltar Pound', ''),
('Greece', 'GR', 'GRC', '30', 'EUR', 'Euro', ''),
('Greenland', 'GL', 'GRL', '299', 'DKK', 'Danish Krone', ''),
('Grenada', 'GD', 'GRD', '1-473', 'XCD', 'East Caribbean Dollar', ''),
('Guadeloupe', 'GP', 'GLP', '590', 'EUR', 'Euro', ''),
('Guam', 'GU', 'GUM', '1-671', 'USD', 'US Dollar', ''),
('Guatemala', 'GT', 'GTM', '502', 'GTQ', 'Quetzal', ''),
('Guernsey', 'GG', 'GGY', '44', 'GBP', 'Pound Sterling', ''),
('Guinea', 'GN', 'GIN', '224', 'GNF', 'Guinea Franc', ''),
('Guinea-Bissau', 'GW', 'GNB', '245', 'XOF', 'CFA Franc BCEAO', ''),
('Guyana', 'GY', 'GUY', '592', 'GYD', 'Guyana Dollar', ''),
('Haiti', 'HT', 'HTI', '509', 'USD', 'US Dollar', ''),
('Heard Island and McDonald Islands', 'HM', 'HMD', '672', 'AUD', 'Australian Dollar', ''),
('Holy See (Vatican City State)', 'VA', 'VAT', '39-06', 'EUR', 'Euro', ''),
('Honduras', 'HN', 'HND', '504', 'HNL', 'Lempira', ''),
('Hong Kong', 'HK', 'HKG', '852', 'HKD', 'Hong Kong Dollar', ''),
( 'Hungary', 'HU', 'HUN', '36', 'HUF', 'Forint', ''),
( 'Iceland', 'IS', 'ISL', '354', 'ISK', 'Iceland Krona', ''),
( 'India', 'IN', 'IND', '91', 'INR', 'Indian Rupee', ''),
( 'Indonesia', 'ID', 'IDN', '62', 'IDR', 'Rupiah', ''),
( 'Iran, Islamic Republic of', 'IR', 'IRN', '98', 'IRR', 'Iranian Rial', ''),
( 'Iraq', 'IQ', 'IRQ', '964', 'IQD', 'Iraqi Dinar', ''),
( 'Ireland', 'IE', 'IRL', '353', 'EUR', 'Euro', ''),
( 'Isle of Man', 'IM', 'IMN', '44', 'GBP', 'Pound Sterling', ''),
( 'Israel', 'IL', 'ISR', '972', 'ILS', 'New Israeli Sheqel', ''),
( 'Italy', 'IT', 'ITA', '39', 'EUR', 'Euro', ''),
( 'Jamaica', 'JM', 'JAM', '1-876', 'JMD', 'Jamaican Dollar', ''),
( 'Japan', 'JP', 'JPN', '81', 'JPY', 'Yen', ''),
( 'Jersey', 'JE', 'JEY', '44', 'GBP', 'Pound Sterling', ''),
( 'Jordan', 'JO', 'JOR', '962', 'JOD', 'Jordanian Dinar', ''),
( 'Kazakhstan', 'KZ', 'KAZ', '7', 'KZT', 'Tenge', ''),
( 'Kenya', 'KE', 'KEN', '254', 'KES', 'Kenyan Shilling', ''),
( 'Kiribati', 'KI', 'KIR', '686', 'AUD', 'Australian Dollar', ''),
( 'Korea, Democratic People''s Republic of', 'KP', 'PRK', '850', 'KPW', 'North Korean Won', ''),
( 'Korea, Republic of', 'KR', 'KOR', '82', 'KRW', 'Won', ''),
( 'Kuwait', 'KW', 'KWT', '965', 'KWD', 'Kuwaiti Dinar', ''),
( 'Kyrgyzstan', 'KG', 'KGZ', '996', 'KGS', 'Som', ''),
( 'Lao People''s Democratic Republic', 'LA', 'LAO', '856', 'LAK', 'Kip', ''),
( 'Latvia', 'LV', 'LVA', '371', 'EUR', 'Euro', ''),
( 'Lebanon', 'LB', 'LBN', '961', 'LBP', 'Lebanese Pound', ''),
( 'Lesotho', 'LS', 'LSO', '266', 'ZAR', 'Rand', ''),
( 'Liberia', 'LR', 'LBR', '231', 'LRD', 'Liberian Dollar', ''),
( 'Libya', 'LY', 'LBY', '218', 'LYD', 'Libyan Dinar', ''),
( 'Liechtenstein', 'LI', 'LIE', '423', 'CHF', 'Swiss Franc', ''),
( 'Lithuania', 'LT', 'LTU', '370', 'EUR', 'Euro', ''),
( 'Luxembourg', 'LU', 'LUX', '352', 'EUR', 'Euro', ''),
( 'Macao', 'MO', 'MAC', '853', 'MOP', 'Pataca', ''),
( 'Macedonia, the Former Yugoslav Republic of', 'MK', 'MKD', '389', 'MKD', 'Denar', ''),
( 'Madagascar', 'MG', 'MDG', '261', 'MGA', 'Malagasy Ariary', ''),
( 'Malawi', 'MW', 'MWI', '265', 'MWK', 'Kwacha', ''),
( 'Malaysia', 'MY', 'MYS', '60', 'MYR', 'Malaysian Ringgit', ''),
( 'Maldives', 'MV', 'MDV', '960', 'MVR', 'Rufiyaa', ''),
( 'Mali', 'ML', 'MLI', '223', 'XOF', 'CFA Franc BCEAO', ''),
( 'Malta', 'MT', 'MLT', '356', 'EUR', 'Euro', ''),
( 'Marshall Islands', 'MH', 'MHL', '692', 'USD', 'US Dollar', ''),
( 'Martinique', 'MQ', 'MTQ', '596', 'EUR', 'Euro', ''),
( 'Mauritania', 'MR', 'MRT', '222', 'MRO', 'Ouguiya', ''),
( 'Mauritius', 'MU', 'MUS', '230', 'MUR', 'Mauritius Rupee', ''),
( 'Mayotte', 'YT', 'MYT', '262', 'EUR', 'Euro', ''),
( 'Mexico', 'MX', 'MEX', '52', 'MXN', 'Mexican Peso', ''),
( 'Micronesia, Federated States of', 'FM', 'FSM', '691', 'USD', 'US Dollar', ''),
( 'Moldova, Republic of', 'MD', 'MDA', '373', 'MDL', 'Moldovan Leu', ''),
( 'Monaco', 'MC', 'MCO', '377', 'EUR', 'Euro', ''),
( 'Mongolia', 'MN', 'MNG', '976', 'MNT', 'Tugrik', ''),
( 'Montenegro', 'ME', 'MNE', '382', 'EUR', 'Euro', ''),
( 'Montserrat', 'MS', 'MSR', '1-664', 'XCD', 'East Caribbean Dollar', ''),
( 'Morocco', 'MA', 'MAR', '212', 'MAD', 'Moroccan Dirham', ''),
( 'Mozambique', 'MZ', 'MOZ', '258', 'MZN', 'Mozambique Metical', ''),
( 'Myanmar', 'MM', 'MMR', '95', 'MMK', 'Kyat', ''),
( 'Namibia', 'NA', 'NAM', '264', 'ZAR', 'Rand', ''),
( 'Nauru', 'NR', 'NRU', '674', 'AUD', 'Australian Dollar', ''),
( 'Nepal', 'NP', 'NPL', '977', 'NPR', 'Nepalese Rupee', ''),
( 'Netherlands', 'NL', 'NLD', '31', 'EUR', 'Euro', ''),
( 'New Caledonia', 'NC', 'NCL', '687', 'XPF', 'CFP Franc', ''),
( 'New Zealand', 'NZ', 'NZL', '64', 'NZD', 'New Zealand Dollar', ''),
( 'Nicaragua', 'NI', 'NIC', '505', 'NIO', 'Cordoba Oro', ''),
( 'Niger', 'NE', 'NER', '227', 'XOF', 'CFA Franc BCEAO', ''),
( 'Nigeria', 'NG', 'NGA', '234', 'NGN', 'Naira', ''),
( 'Niue', 'NU', 'NIU', '683', 'NZD', 'New Zealand Dollar', ''),
( 'Norfolk Island', 'NF', 'NFK', '672', 'AUD', 'Australian Dollar', ''),
( 'Northern Mariana Islands', 'MP', 'MNP', '1-670', 'USD', 'US Dollar', ''),
( 'Norway', 'NO', 'NOR', '47', 'NOK', 'Norwegian Krone', ''),
( 'Oman', 'OM', 'OMN', '968', 'OMR', 'Rial Omani', ''),
( 'Pakistan', 'PK', 'PAK', '92', 'PKR', 'Pakistan Rupee', ''),
( 'Palau', 'PW', 'PLW', '680', 'USD', 'US Dollar', ''),
( 'Palestine, State of', 'PS', 'PSE', '970', '', '', ''),
( 'Panama', 'PA', 'PAN', '507', 'USD', 'US Dollar', ''),
( 'Papua New Guinea', 'PG', 'PNG', '675', 'PGK', 'Kina', ''),
( 'Paraguay', 'PY', 'PRY', '595', 'PYG', 'Guarani', ''),
( 'Peru', 'PE', 'PER', '51', 'PEN', 'Nuevo Sol', ''),
( 'Philippines', 'PH', 'PHL', '63', 'PHP', 'Philippine Peso', ''),
( 'Pitcairn', 'PN', 'PCN', '870', 'NZD', 'New Zealand Dollar', ''),
( 'Poland', 'PL', 'POL', '48', 'PLN', 'Zloty', ''),
( 'Portugal', 'PT', 'PRT', '351', 'EUR', 'Euro', ''),
( 'Puerto Rico', 'PR', 'PRI', '1', 'USD', 'US Dollar', ''),
( 'Qatar', 'QA', 'QAT', '974', 'QAR', 'Qatari Rial', ''),
( 'Romania', 'RO', 'ROU', '40', 'RON', 'New Romanian Leu', ''),
( 'Russian Federation', 'RU', 'RUS', '7', 'RUB', 'Russian Ruble', ''),
( 'Rwanda', 'RW', 'RWA', '250', 'RWF', 'Rwanda Franc', ''),
( 'Réunion', 'RE', 'REU', '262', 'EUR', 'Euro', ''),
( 'Saint Barthélemy', 'BL', 'BLM', '590', 'EUR', 'Euro', ''),
( 'Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', '290', 'SHP', 'Saint Helena Pound', ''),
( 'Saint Kitts and Nevis', 'KN', 'KNA', '1-869', 'XCD', 'East Caribbean Dollar', ''),
( 'Saint Lucia', 'LC', 'LCA', '1-758', 'XCD', 'East Caribbean Dollar', ''),
( 'Saint Martin (French part)', 'MF', 'MAF', '590', 'EUR', 'Euro', ''),
( 'Saint Pierre and Miquelon', 'PM', 'SPM', '508', 'EUR', 'Euro', ''),
( 'Saint Vincent and the Grenadines', 'VC', 'VCT', '1-784', 'XCD', 'East Caribbean Dollar', ''),
( 'Samoa', 'WS', 'WSM', '685', 'WST', 'Tala', ''),
( 'San Marino', 'SM', 'SMR', '378', 'EUR', 'Euro', ''),
( 'Sao Tome and Principe', 'ST', 'STP', '239', 'STD', 'Dobra', ''),
( 'Saudi Arabia', 'SA', 'SAU', '966', 'SAR', 'Saudi Riyal', ''),
( 'Senegal', 'SN', 'SEN', '221', 'XOF', 'CFA Franc BCEAO', ''),
( 'Serbia', 'RS', 'SRB', '381', 'RSD', 'Serbian Dinar', ''),
( 'Seychelles', 'SC', 'SYC', '248', 'SCR', 'Seychelles Rupee', ''),
( 'Sierra Leone', 'SL', 'SLE', '232', 'SLL', 'Leone', ''),
( 'Singapore', 'SG', 'SGP', '65', 'SGD', 'Singapore Dollar', ''),
( 'Sint Maarten (Dutch part)', 'SX', 'SXM', '1-721', 'ANG', 'Netherlands Antillean Guilder', ''),
( 'Slovakia', 'SK', 'SVK', '421', 'EUR', 'Euro', ''),
( 'Slovenia', 'SI', 'SVN', '386', 'EUR', 'Euro', ''),
( 'Solomon Islands', 'SB', 'SLB', '677', 'SBD', 'Solomon Islands Dollar', ''),
( 'Somalia', 'SO', 'SOM', '252', 'SOS', 'Somali Shilling', ''),
( 'South Africa', 'ZA', 'ZAF', '27', 'ZAR', 'Rand', ''),
( 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', '500', '', '', ''),
( 'South Sudan', 'SS', 'SSD', '211', 'SSP', 'South Sudanese Pound', ''),
( 'Spain', 'ES', 'ESP', '34', 'EUR', 'Euro', ''),
( 'Sri Lanka', 'LK', 'LKA', '94', 'LKR', 'Sri Lanka Rupee', ''),
( 'Sudan', 'SD', 'SDN', '249', 'SDG', 'Sudanese Pound', ''),
( 'Suriname', 'SR', 'SUR', '597', 'SRD', 'Surinam Dollar', ''),
( 'Svalbard and Jan Mayen', 'SJ', 'SJM', '47', 'NOK', 'Norwegian Krone', ''),
( 'Swaziland', 'SZ', 'SWZ', '268', 'SZL', 'Lilangeni', ''),
( 'Sweden', 'SE', 'SWE', '46', 'SEK', 'Swedish Krona', ''),
( 'Switzerland', 'CH', 'CHE', '41', 'CHF', 'Swiss Franc', ''),
( 'Syrian Arab Republic', 'SY', 'SYR', '963', 'SYP', 'Syrian Pound', ''),
( 'Taiwan, Province of China', 'TW', 'TWN', '886', 'TWD', 'New Taiwan Dollar', ''),
( 'Tajikistan', 'TJ', 'TJK', '992', 'TJS', 'Somoni', ''),
( 'Tanzania, United Republic of', 'TZ', 'TZA', '255', 'TZS', 'Tanzanian Shilling', ''),
( 'Thailand', 'TH', 'THA', '66', 'THB', 'Baht', ''),
( 'Timor-Leste', 'TL', 'TLS', '670', 'USD', 'US Dollar', ''),
( 'Togo', 'TG', 'TGO', '228', 'XOF', 'CFA Franc BCEAO', ''),
( 'Tokelau', 'TK', 'TKL', '690', 'NZD', 'New Zealand Dollar', ''),
( 'Tonga', 'TO', 'TON', '676', 'TOP', 'Pa’anga', ''),
( 'Trinidad and Tobago', 'TT', 'TTO', '1-868', 'TTD', 'Trinidad and Tobago Dollar', ''),
( 'Tunisia', 'TN', 'TUN', '216', 'TND', 'Tunisian Dinar', ''),
( 'Turkey', 'TR', 'TUR', '90', 'TRY', 'Turkish Lira', ''),
( 'Turkmenistan', 'TM', 'TKM', '993', 'TMT', 'Turkmenistan New Manat', ''),
( 'Turks and Caicos Islands', 'TC', 'TCA', '1-649', 'USD', 'US Dollar', ''),
( 'Tuvalu', 'TV', 'TUV', '688', 'AUD', 'Australian Dollar', ''),
( 'Uganda', 'UG', 'UGA', '256', 'UGX', 'Uganda Shilling', ''),
( 'Ukraine', 'UA', 'UKR', '380', 'UAH', 'Hryvnia', ''),
( 'United Arab Emirates', 'AE', 'ARE', '971', 'AED', 'UAE Dirham', ''),
( 'United Kingdom', 'GB', 'GBR', '44', 'GBP', 'Pound Sterling', ''),
( 'United States', 'US', 'USA', '1', 'USD', 'US Dollar', ''),
( 'United States Minor Outlying Islands', 'UM', 'UMI', '1', 'USD', 'US Dollar', ''),
( 'Uruguay', 'UY', 'URY', '598', 'UYU', 'Peso Uruguayo', ''),
( 'Uzbekistan', 'UZ', 'UZB', '998', 'UZS', 'Uzbekistan Sum', ''),
( 'Vanuatu', 'VU', 'VUT', '678', 'VUV', 'Vatu', ''),
( 'Venezuela, Bolivarian Republic of', 'VE', 'VEN', '58', 'VEF', 'Bolivar', ''),
( 'Viet Nam', 'VN', 'VNM', '84', 'VND', 'Dong', ''),
( 'Virgin Islands, British', 'VG', 'VGB', '1-284', 'USD', 'US Dollar', ''),
( 'Virgin Islands, U.S.', 'VI', 'VIR', '1-340', 'USD', 'US Dollar', ''),
( 'Wallis and Futuna', 'WF', 'WLF', '681', 'XPF', 'CFP Franc', ''),
( 'Western Sahara', 'EH', 'ESH', '212', 'MAD', 'Moroccan Dirham', ''),
( 'Yemen', 'YE', 'YEM', '967', 'YER', 'Yemeni Rial', ''),
( 'Zambia', 'ZM', 'ZMB', '260', 'ZMW', 'Zambian Kwacha', ''),
( 'Zimbabwe', 'ZW', 'ZWE', '263', 'ZWL', 'Zimbabwe Dollar', ''),
( 'Åland Islands', 'AX', 'ALA', '358', 'EUR', 'Euro', '');
